
if __name__ == "__main__":
    # basic array manipulation
    darr = []
    darr.append(1)
    darr.append(2)
    darr.append(3)
    print("After 3 appends:")
    print(darr)
    darr.insert(0, 10)
    darr.insert(1, 11)
    print("After insert 10 on 0 and 11 on 1")
    print(darr)
    print("Popping:")
    print(darr.pop())
    print(darr.pop(1))
    print(darr)
    print("Remove 1:")
    darr.remove(1)
    print(darr)
    print("Reverse darr:")
    darr.reverse()
    print(darr)
    darr.append(1)
    darr.insert(0, 1)
    print("Occurences of 1: {}".format(darr.count(1)))
    print(darr)
    print("Sorting:")
    darr.sort()
    print(darr)
    print("Reverse sorting:")
    darr.sort(reverse=True)
    print(darr)
    # combining two arrays
    new_darr = ['33', '22', '11']
    darr.extend(new_darr)
    print("Extended with new array {}".format(new_darr))
    print(darr)
    darr.sort(key = lambda x: (isinstance(x, str), x))
    print("Sort mixed array: {}".format(darr))
